// Permission system for sidebar menu authorization

export enum PERMISSIONS {
  CREATE_ORDER = 'CREATE_ORDER',
  VIEW_MY_ORDERS = 'VIEW_MY_ORDERS',
  RECEIVE_SHIPMENT = 'RECEIVE_SHIPMENT',
  APPROVE_ORDERS = 'APPROVE_ORDERS',
  PRODUCTION_PLANNING = 'PRODUCTION_PLANNING',
  ALLOCATION_MANAGEMENT = 'ALLOCATION_MANAGEMENT',
  CREATE_SHIPMENT = 'CREATE_SHIPMENT',
  PRODUCTION_SCHEDULE = 'PRODUCTION_SCHEDULE',
  MATERIAL_INVENTORY = 'MATERIAL_INVENTORY',
  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
  CATEGORY_MANAGEMENT = 'CATEGORY_MANAGEMENT',
  INGREDIENT_MANAGEMENT = 'INGREDIENT_MANAGEMENT',
  BILLING_MANAGEMENT = 'BILLING_MANAGEMENT',
  REVENUE_REPORTS = 'REVENUE_REPORTS',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ROLE_PERMISSION_MANAGEMENT = 'ROLE_PERMISSION_MANAGEMENT',
  STORE_MANAGEMENT = 'STORE_MANAGEMENT',
}

export const ROLE_PERMISSIONS: Record<string, PERMISSIONS[]> = {
  STORE_STAFF: [
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.VIEW_MY_ORDERS,
    PERMISSIONS.RECEIVE_SHIPMENT,
  ],
  COORDINATOR: [
    PERMISSIONS.APPROVE_ORDERS,
    PERMISSIONS.PRODUCTION_PLANNING,
    PERMISSIONS.ALLOCATION_MANAGEMENT,
    PERMISSIONS.CREATE_SHIPMENT,
  ],
  KITCHEN_STAFF: [
    PERMISSIONS.PRODUCTION_SCHEDULE,
    PERMISSIONS.MATERIAL_INVENTORY,
  ],
  MANAGER: [
    PERMISSIONS.PRODUCT_MANAGEMENT,
    PERMISSIONS.CATEGORY_MANAGEMENT,
    PERMISSIONS.INGREDIENT_MANAGEMENT,
    PERMISSIONS.BILLING_MANAGEMENT,
    PERMISSIONS.REVENUE_REPORTS,
  ],
  ADMIN: [
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.ROLE_PERMISSION_MANAGEMENT,
    PERMISSIONS.STORE_MANAGEMENT,
  ],
};
